[phases.setup]
nixPkgs = ["php84", "php84Extensions.intl", "php84Extensions.zip", "php84Extensions.pgsql", "php84Extensions.pdo_pgsql", "php84Extensions.opcache"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-scripts --no-interaction", "npm ci"]

[phases.build]
cmds = ["npm run build", "php artisan optimize"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
